const keyCodes = [
	{ keys: "0", codes: "That key has no keycode" },
	{ keys: "3", codes: "break" },
	{ keys: "8", codes: "backspace / delete" },
	{ keys: "9", codes: "tab" },
	{ keys: "12", codes: "clear" },
	{ keys: "13", codes: "enter" },
	{ keys: "16", codes: "shift" },
	{ keys: "17", codes: "ctrl" },
	{ keys: "18", codes: "alt" },
	{ keys: "19", codes: "pause/break" },
	{ keys: "20", codes: "caps lock" },
	{ keys: "21", codes: "hangul" },
	{ keys: "25", codes: "hanja" },
	{ keys: "27", codes: "escape" },
	{ keys: "28", codes: "conversion" },
	{ keys: "29", codes: "non-conversion" },
	{ keys: "32", codes: "spacebar" },
	{ keys: "33", codes: "page up" },
	{ keys: "34", codes: "page down" },
	{ keys: "35", codes: "end" },
	{ keys: "36", codes: "home" },
	{ keys: "37", codes: "left arrow" },
	{ keys: "38", codes: "up arrow" },
	{ keys: "39", codes: "right arrow" },
	{ keys: "40", codes: "down arrow" },
	{ keys: "41", codes: "select" },
	{ keys: "42", codes: "print" },
	{ keys: "43", codes: "execute" },
	{ keys: "44", codes: "Print Screen" },
	{ keys: "45", codes: "insert" },
	{ keys: "46", codes: "delete" },
	{ keys: "47", codes: "help" },
	{ keys: "48", codes: "0" },
	{ keys: "49", codes: "1" },
	{ keys: "50", codes: "2" },
	{ keys: "51", codes: "3" },
	{ keys: "52", codes: "4" },
	{ keys: "53", codes: "5" },
	{ keys: "54", codes: "6" },
	{ keys: "55", codes: "7" },
	{ keys: "56", codes: "8" },
	{ keys: "57", codes: "9" },
	{ keys: "58", codes: ":" },
	{ keys: "59", codes: "semicolon (firefox), equals" },
	{ keys: "60", codes: "<" },
	{ keys: "61", codes: "equals (firefox)" },
	{ keys: "63", codes: "ß" },
	{ keys: "64", codes: "@ (firefox)" },
	{ keys: "65", codes: "a" },
	{ keys: "66", codes: "b" },
	{ keys: "67", codes: "c" },
	{ keys: "68", codes: "d" },
	{ keys: "69", codes: "e" },
	{ keys: "70", codes: "f" },
	{ keys: "71", codes: "g" },
	{ keys: "72", codes: "h" },
	{ keys: "73", codes: "i" },
	{ keys: "74", codes: "j" },
	{ keys: "75", codes: "k" },
	{ keys: "76", codes: "l" },
	{ keys: "77", codes: "m" },
	{ keys: "78", codes: "n" },
	{ keys: "79", codes: "o" },
	{ keys: "80", codes: "p" },
	{ keys: "81", codes: "q" },
	{ keys: "82", codes: "r" },
	{ keys: "83", codes: "s" },
	{ keys: "84", codes: "t" },
	{ keys: "85", codes: "u" },
	{ keys: "86", codes: "v" },
	{ keys: "87", codes: "w" },
	{ keys: "88", codes: "x" },
	{ keys: "89", codes: "y" },
	{ keys: "90", codes: "z" },
	{ keys: "91", codes: "Windows Key / Left ⌘ / Chromebook Search key" },
	{ keys: "92", codes: "right window key" },
	{ keys: "93", codes: "Windows Menu / Right ⌘" },
	{ keys: "95", codes: "sleep" },
	{ keys: "96", codes: "numpad 0" },
	{ keys: "97", codes: "numpad 1" },
	{ keys: "98", codes: "numpad 2" },
	{ keys: "99", codes: "numpad 3" },
	{ keys: "100", codes: "numpad 4" },
	{ keys: "101", codes: "numpad 5" },
	{ keys: "102", codes: "numpad 6" },
	{ keys: "103", codes: "numpad 7" },
	{ keys: "104", codes: "numpad 8" },
	{ keys: "105", codes: "numpad 9" },
	{ keys: "106", codes: "multiply" },
	{ keys: "107", codes: "add" },
	{ keys: "108", codes: "numpad period (firefox)" },
	{ keys: "109", codes: "subtract" },
	{ keys: "110", codes: "decimal point" },
	{ keys: "111", codes: "divide" },
	{ keys: "112", codes: "f1" },
	{ keys: "113", codes: "f2" },
	{ keys: "114", codes: "f3" },
	{ keys: "115", codes: "f4" },
	{ keys: "116", codes: "f5" },
	{ keys: "117", codes: "f6" },
	{ keys: "118", codes: "f7" },
	{ keys: "119", codes: "f8" },
	{ keys: "120", codes: "f9" },
	{ keys: "121", codes: "f10" },
	{ keys: "122", codes: "f11" },
	{ keys: "123", codes: "f12" },
	{ keys: "124", codes: "f13" },
	{ keys: "125", codes: "f14" },
	{ keys: "126", codes: "f15" },
	{ keys: "127", codes: "f16" },
	{ keys: "128", codes: "f17" },
	{ keys: "129", codes: "f18" },
	{ keys: "130", codes: "f19" },
	{ keys: "131", codes: "f20" },
	{ keys: "132", codes: "f21" },
	{ keys: "133", codes: "f22" },
	{ keys: "134", codes: "f23" },
	{ keys: "135", codes: "f24" },
	{ keys: "136", codes: "f25" },
	{ keys: "137", codes: "f26" },
	{ keys: "138", codes: "f27" },
	{ keys: "139", codes: "f28" },
	{ keys: "140", codes: "f29" },
	{ keys: "141", codes: "f30" },
	{ keys: "142", codes: "f31" },
	{ keys: "143", codes: "f32" },
	{ keys: "144", codes: "num lock" },
	{ keys: "145", codes: "scroll lock" },
	{ keys: "151", codes: "airplane mode" },
	{ keys: "160", codes: "^" },
	{ keys: "161", codes: "!" },
	{ keys: "162", codes: "؛ (arabic semicolon)" },
	{ keys: "163", codes: "#" },
	{ keys: "164", codes: "$" },
	{ keys: "165", codes: "ù" },
	{ keys: "166", codes: "page backward" },
	{ keys: "167", codes: "page forward" },
	{ keys: "168", codes: "refresh" },
	{ keys: "169", codes: "closing paren (AZERTY)" },
	{ keys: "170", codes: "*" },
	{ keys: "171", codes: "~ + * key" },
	{ keys: "172", codes: "home key" },
	{ keys: "173", codes: "minus (firefox), mute/unmute" },
	{ keys: "174", codes: "decrease volume level" },
	{ keys: "175", codes: "increase volume level" },
	{ keys: "176", codes: "next" },
	{ keys: "177", codes: "previous" },
	{ keys: "178", codes: "stop" },
	{ keys: "179", codes: "play/pause" },
	{ keys: "180", codes: "e-mail" },
	{ keys: "181", codes: "mute/unmute (firefox)" },
	{ keys: "182", codes: "decrease volume level (firefox)" },
	{ keys: "183", codes: "increase volume level (firefox)" },
	{ keys: "186", codes: "semi-colon / ñ" },
	{ keys: "187", codes: "equal sign" },
	{ keys: "188", codes: "comma" },
	{ keys: "189", codes: "dash" },
	{ keys: "190", codes: "period" },
	{ keys: "191", codes: "forward slash / ç" },
	{ keys: "192", codes: "grave accent / ñ / æ / ö" },
	{ keys: "193", codes: "?, / or °" },
	{ keys: "194", codes: "numpad period (chrome)" },
	{ keys: "219", codes: "open bracket" },
	{ keys: "220", codes: "back slash" },
	{ keys: "221", codes: "close bracket / å" },
	{ keys: "222", codes: "single quote / ø / ä" },
	{ keys: "223", codes: "`" },
	{ keys: "224", codes: "left or right ⌘ key (firefox)" },
	{ keys: "225", codes: "altgr" },
	{ keys: "226", codes: "< /git >, left back slash" },
	{ keys: "230", codes: "GNOME Compose Key" },
	{ keys: "231", codes: "ç" },
	{ keys: "233", codes: "XF86Forward" },
	{ keys: "234", codes: "XF86Back" },
	{ keys: "235", codes: "non-conversion" },
	{ keys: "240", codes: "alphanumeric" },
	{ keys: "242", codes: "hiragana/katakana" },
	{ keys: "243", codes: "half-width/full-width" },
	{ keys: "244", codes: "kanji" },
	{ keys: "251", codes: "unlock trackpad (Chrome/Edge)" },
	{ keys: "255", codes: "toggle touchpad" },
];
function loadTableData(items) {
	const x = document.getElementById("Body");
	items.forEach((item) => {
		let row = x.insertRow();
		let keys = row.insertCell(0);
		keys.innerHTML = item.keys;
		let codes = row.insertCell(1);
		codes.innerHTML = item.codes;
	});
}
loadTableData(keyCodes);
loadTableData([]);
